1044 - Change Default Message For Associated Consultations
archesproject/arches-her pull request #1046
Opened 2023-02-02 13:59 UTC by csmith-he

Remedies issue #1044

- resourceinstanceid object added to the resourceDataConfig for Activity, Area, Aircraft, Maritime, Monument and Person
- code added to provide a message to the user when they either do not have permissions to access associated consultation data or when there are no associated consultation records

2023-07-14 18:45 UTC, chiatt requested changes
This looks good and worked as expected for me, but I had to also add the `resourceinstanceid` to the `resourceDataConfig` of `consultation.js` as you've done for activity, area, historic-aircraft, etc.

2023-07-14 18:45 UTC, chiatt commented on arches_her/templates/views/components/reports/scenes/resources.htm
> +                    <p class="aher-table-aria-describedby" id="related-application-area-table_info">Related application area table.</p>
I think this line is too close to the heading above it. Maybe it was in place for testing? It could probably just be removed. 

![image](https://github.com/archesproject/arches-her/assets/1877663/7c16353f-2287-416b-820c-01a25f25d6f3)

2023-07-18 15:35 UTC, csmith-he commented
Hi @chiatt 
Thanks for getting back to me; I'll take a look at this tomorrow (19 Jul)

2023-07-21 07:25 UTC, csmith-he commented on arches_her/templates/views/components/reports/scenes/resources.htm
> +                    <p class="aher-table-aria-describedby" id="related-application-area-table_info">Related application area table.</p>
@chiatt - Thanks for being patient while I took a look at this.

I've amended the consultation.js so the resourceinstanceid is in the resourceDataConfig.

I spoke to @phudson-he about that label.  It's there for accessibility reasons (screen readers) but should have been hidden by styling - I hadn't realised this as the styling was already present in our repo for Keystone but didn't seem to be in arches-her.  I've now added it to report_templates.css so the label should not longer be visible.

2023-08-03 15:51 UTC, chiatt approved these changes

2023-08-03 15:55 UTC, merged