#1134 Resource Descriptors handles new string format
archesproject/arches-her pull request #1139
Opened 2024-04-19 15:33 UTC by csmith-he

Fixes #1134 

Handles display name, display description and map popup values in the new string format.

2024-04-23 15:13 UTC, aj-he commented on arches_her/views/resource.py
> +                    map_popup = document['_source']['map_popup'][0]['value']
this gets the first display descriptor. It should get the one for the active language
![image](https://github.com/archesproject/arches-her/assets/25295526/4c227850-87f8-46f3-981e-84c22668a3b3)

2024-04-23 17:11 UTC, aj-he requested changes
use the active language to determine the value

2024-04-27 07:33 UTC, aj-he commented
@csmith-he I realised that this whole ResourceDescriptor was missing important content as the main RD has added userid and permissions info since first created. So I thought we could use the main RD as a base class, call the base get function and then inject the active_consultation data if it was a consultation.

I mocked up an example, but while testing I realised that the active consultations page was not using this. So I looked back at the blame and there used to be another search page for consultations that used a custom popup.

This functionality was removed in 2021, but the descriptor was not. Therefore, we could probably remove the whole custom descriptor. Can you test by commenting out the route in urls.py and seeing if there are any issues? If not, we should remove it.

2024-04-29 11:14 UTC, csmith-he commented
@aj-he No adverse effects I could see by removing the resource descriptor entirely and references to it so I've done that.

2024-04-29 12:24 UTC, aj-he approved these changes
It all works for me

2024-04-29 12:24 UTC, merged