Multiple fixes for report templates
archesproject/arches-her pull request #931
Opened 2022-05-06 13:19 UTC by aj-he

addresses the following report template issues

#796
#799
#804
#806
#808
#813
#816
#817
#825
#826
#827
#830
#831
#832
#833
#834
#842
#846
#847
#860
#863
#864
#878
#885
#922
#923

2022-05-06 13:26 UTC, aj-he commented
Hi @chiatt, apologies for the size of this PR. They are only small changes but go across a lot of issues so I thought that as this content was large it would be best for you to review, so you guys understand what is going in. The others are smaller so should be easier for you to track from afar.

2022-05-06 22:21 UTC, chiatt reviewed
Overall this looks great. I just saw one error which I've commented on inline. Also, I noticed that #847 is listed in the addressed tickets, but it doesn't look like it's resolved.

2022-05-06 22:21 UTC, chiatt commented on arches_her/media/js/views/components/reports/scenes/resources.js
> +                        for (const element of x?.['Associated Heritage Asset, Area or Artefact']?.['instance_details']) {
While testing #863, I ran into this error at line 122: 
![image](https://user-images.githubusercontent.com/1877663/167221258-ca20a620-c97e-4e2d-bdd7-a6459c22fcd6.png)

2022-05-06 22:36 UTC, njkim requested changes
#825 "Associated Heritage Asset, Area or Artefact" still not showing, (associate file seems to be fixed.
#827 Activity model location tab is still not working in report view, while it is working in the editor view. (Other models' locations seem to be working properly)

2022-05-09 14:00 UTC, aj-he commented
@chiatt @njkim thanks for reviewing. There is another ticket #915 that @RobOatesHistoricEngland is working on which is a broad fix for the Associated Resources tabs across multiple models that I think will fix these remaining issues. I'll be reviewing it with him in the morning and will then add it to this PR. There has been a general issue with cardinality being different for data going into shared scenes, so hopefully this will fix it.

2022-05-11 10:45 UTC, aj-he commented
> Overall this looks great. I just saw one error which I've commented on inline. Also, I noticed that #847 is listed in the addressed tickets, but it doesn't look like it's resolved.

@chiatt you are right, I think this is a new feature rather than a bug. I will remove it from the resolved tickets list.

2022-05-11 11:50 UTC, aj-he commented on arches_her/media/js/views/components/reports/scenes/resources.js
> +                        for (const element of x?.['Associated Heritage Asset, Area or Artefact']?.['instance_details']) {
This is now resolved from #915

2022-05-11 11:51 UTC, aj-he commented
> #825 "Associated Heritage Asset, Area or Artefact" still not showing, (associate file seems to be fixed. #827 Activity model location tab is still not working in report view, while it is working in the editor view. (Other models' locations seem to be working properly)

@njkim these are no longer an issue from my testing. Please can you check your end?

2022-05-11 17:45 UTC, chiatt approved these changes
Looks good to me!

2022-05-12 01:09 UTC, njkim approved these changes
Look great

2022-05-12 01:09 UTC, merged