Make the digital object filename a clickable link
archesproject/arches-her pull request #947
Opened 2022-05-17 10:47 UTC by phudson-he

2022-05-18 08:19 UTC, aj-he requested changes
See the comments on the file link not forming correctly.

2022-05-18 08:19 UTC, aj-he commented on arches_her/media/js/views/components/reports/digital-object.js
> +                                href: self.getNodeValue(self.resource(), 'file content', 'file'),
This seems to be creating a bad link address. In this example the link should be *http://localhost:8002/files/d0e52338-cd3c-11ec-872b-0242ac130007* but it is appearing as *http://localhost:8002/files/d0e52338-cd3c-11ec-872b-0242ac130007%20%7C%20/files/d0e9e4ae-cd3c-11ec-872b-0242ac130007*

![image](https://user-images.githubusercontent.com/25295526/168991688-ad853092-c60a-4d4f-99d2-dd574cde9029.png)

2022-05-18 08:19 UTC, aj-he commented on arches_her/media/js/views/components/reports/digital-object.js
> +                                href: self.getNodeValue(self.resource(), 'file content', 'file'),
... and what I can see from the Dev Tools...
![image](https://user-images.githubusercontent.com/25295526/168992218-561f5b2e-5f4e-45d0-807d-90a0f50656c8.png)

2022-05-23 14:15 UTC, phudson-he commented on arches_her/media/js/views/components/reports/digital-object.js
> +                                href: self.getNodeValue(self.resource(), 'file content', 'file'),
Now enabled multiple files to display as expected in report view/editor

2022-05-23 14:24 UTC, aj-he approved these changes

2022-05-23 14:28 UTC, aj-he commented
fixes #794 also

2022-05-23 14:36 UTC, merged