Heritage Story Report changes
archesproject/arches-her pull request #978
Opened 2022-05-24 13:47 UTC by csmith-he

Fixes #872 #873 #919

2022-05-24 14:26 UTC, aj-he requested changes
Could you format it so that there is a space between comma and following type...

![image](https://user-images.githubusercontent.com/25295526/170054877-a5f4d735-e554-4e0e-bdff-33a2d6900237.png)

I am also getting an empty row in Periods desptite not having anything in Temporal Coverage. Adding a Period and then removing it causes the row to go away but when I refresh the resource it comes back again.
![image](https://user-images.githubusercontent.com/25295526/170057401-c86d2663-f2dc-4635-a137-5809e4a8ea43.png)

The "Edit Tile" and "Delete Tile" buttons on the Translation rows don't work
![image](https://user-images.githubusercontent.com/25295526/170059653-37bb41d5-925b-46bd-9451-2479d5fce2a4.png)

2022-05-25 10:17 UTC, csmith-he commented
@aj-he: Requested changed made.  Please re-review

2022-05-26 10:13 UTC, aj-he approved these changes

2022-05-26 10:14 UTC, aj-he reviewed
Looks good

2022-05-26 10:14 UTC, merged